### ISSUE TITLE
Topk question about rebuilding user-item graph

### ISSUE THREAD

**Issue by Ricardo-Ping** [HKUDS/DiffMM#1]
Why is topk set to 1 and not some other higher number? Would it work better if it was a higher number? Have you done an experiment on this?

**Comment by yangqin-jiang** [comment]
Thank you for your question. We have tried setting k to a larger number (e.g., 2 and 3), but the experimental results show that a larger k value does not lead to significant performance improvement, but it significantly increases the time needed for modality-aware UI graph reconstruction. Therefore, a sparser multimodal UI graph may be more suitable.

**Comment by Ricardo-Ping** [comment]
Thank you for your answers.
